### ISSUE TITLE
Fails for long URLs

### ISSUE THREAD

**Issue by fenhl** [peterc/webloc#1]
Saving a webloc fails when the URL is longer than 109 characters.

```
irb
irb(main):001:0> require "webloc"
=> true
irb(main):002:0> Webloc.new('https://example.net/loremipsumdolorsitametconsectetueradipiscingelitaeneancommodoligulaegetdoloraeneanmassacu').save('test.webloc')
=> nil
irb(main):003:0> Webloc.new('https://example.net/loremipsumdolorsitametconsectetueradipiscingelitaeneancommodoligulaegetdoloraeneanmassacum').save('test.webloc')
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
	from /Library/Ruby/Gems/2.0.0/gems/webloc-0.0.1/lib/webloc.rb:32:in `data'
	from /Library/Ruby/Gems/2.0.0/gems/webloc-0.0.1/lib/webloc.rb:36:in `block in save'
	from /Library/Ruby/Gems/2.0.0/gems/webloc-0.0.1/lib/webloc.rb:36:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/webloc-0.0.1/lib/webloc.rb:36:in `save'
	from (irb):3
	from /usr/bin/irb:12:in `<main>'
irb(main):004:0> 
```

**Comment by witedragen** [comment]
Yes @peterc please fix this, I get this error on High Sierra with ruby 2.3.7p456. Good programme otherwise!

**Comment by peterc** [comment]
I have no idea how I only just saw this issue - sorry! I have just made a new release (after 11 years!) and this problem seems to have resolved itself - most likely due to changes in how character encoding are handled in modern Rubies.

**Comment by wtn** [comment]
I encountered this problem using Ruby 3.2.3, so please reopen this issue.

In my testing, URI inputs with to 109 characters work, and URI inputs with 110 or more characters give the following exception:
```
webloc.rb:32:in `+': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
```

The exception gets raised [here](https://github.com/peterc/webloc/blob/25d09386277e9286d353e77e6ee8f57dc5920207/lib/webloc.rb#L32).

**Comment by peterc** [comment]
You make a good point, so I'm going to take a look into this out of curiosity, although I suspect the format is barely used nowadays. One thing that jumps to mind that 110 + 18 is 128 and perhaps that is pushing more modern versions of Ruby to treat it like a different character set. I could force the issue in the code, but I think looking at the actual spec for the format might help me do it properly.

**Comment by peterc** [comment]
Resolved in https://github.com/peterc/webloc/pull/2 – v0.2.0 of the gem has been published also. Thanks for the prod on this. I got to enjoy digging into the plist format a bit more. When I first implemented the library, I just reverse engineered the webloc files directly, so now I understand a bit more about what they actually contain!
